project:
  type: website
  output-dir: rendered
  
website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hakkinda.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
