project:
  type: website
  output-dir: rendered
  
website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About        
      - href: hakkinda.qmd
        text: Hakkında        
      - href: blog-posts.qmd
        text: Posts        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
