# Resume of Atilla Özgür (Phd)

- Mönchengladbach Germany/Ankara Türkiye
- +49 0162 5638824 / +90 0533 2515557
- ati.ozgur@gmail.com / aoezguer@constructor.university
- (Last Updated 2024-12-22)


{{< include resume/short-summary-en.md >}}


## Education


| University                       | Department             | Degree   | Start | End  |
|----------------------------------|------------------------|----------|-------|------|
| Middle East Technical University | Electrical Engineering | Bachelor | 1995  | 2003 |
| Atılım University                | Computer Engineering   | Master   | 2004  | 2007 |
| Middle East Technical University | Medical Informatics (Incomplete)   | Master   | 2005  | 2008 |
| Başkent University               | Electrical Engineering | PHD      | 2007  | 2017 |


## Employment History

| Title             | Company     | Start   | End |
|-------------------|-------------|---------|-----|
| Postdoctoral Researcher  | Constructor University Bremen - Mathematics and Logistics| 04/2024 | - |
| Adjunct Professor (Part time)   | Ankara Science University | 09-2024 | 02-2025 |
| Senior Developer  | SMS Digital | 02-2022 | 03-2024 |
| Adjunct Professor (Part time)   | Constructor University | 09-2022 | 02-2024 |
| Assistant Professor | Ankara Yıldırım Beyazıd University - Computer Engineering | 06/2021| 02/2022 |
| Postdoctoral Researcher  | Jacobs University Bremen - Mathematics and Logistics| 01/2018 | 01/2022 |
| Database Administrator  | Turkish Labor Agency | 07/2011 | 12/2017 |
| Software Developer and Build/DevOps Engineer  | Milsoft | 05/2010 | 07/2011 |
| Senior Software Developer  | Tilda Telekom | 10/2009 | 05/2010 |
| Software Trainer  | Freelance | 06/2009 | 10/2009 |
| Software Project Manager  | Turksat | 07/2008 | 06/2009 |
| Software Project Manager  | Simetri | 09/2006 | 04/2008 |
| Software Trainer  | Netsoft | 10/2005 | 12/2006 |
| Software Developer  | Kale Yazılım | 10/2004 | 10/2005 |
| Software Developer  | Veripark | 06/2003 | 10/2004 |



## Peer Reviewed Articles (SCI-E)

{{< include resume/article-list.md >}}

## Other Peer Reviewed Articles

1. Atilla Özgür, Hamit Erdem  Saldırı Tespit Sistemlerinde Kullanılan Kolay Erişilen Makine Öğrenme Algoritmalarının Karşılaştırılması Bilişim Teknolojileri Dergisi, 41-48, 2012
2. Fatih Nar, Osman Erman Okman, Atilla Özgür, M Çetin, “RmSAT-CFAR: Fast and accurate target detection in radar images” in SoftwareX, 2017

- See others in my [google scholar](https://scholar.google.com.tr/citations?user=Q9ll-kcAAAAJ&hl=en) and [Research Gate](https://www.researchgate.net/profile/Atilla_Oezguer) profiles.

## Certifications - Exams (See Long Version for Complete History)

{{< include resume/certificates.md >}}

## Courses I Taught in Universities:

{{< include resume/courses-taught-en.md >}}


* Data Structures (Baskent University, in Turkish, 2 semestres: 2013 and 2014)
* Note: I have taught numerous courses when I was working as an IT Trainer and Senior Developer, mostly general programming, web programming, software management and database courses. 

## Online Presence
1. [google scholar (h-index:9)](https://scholar.google.com.tr/citations?user=Q9ll-kcAAAAJ&hl=en)
2. [researchgate](https://www.researchgate.net/profile/Atilla_Oezguer)
3. [github](https://github.com/ati-ozgur)
4. [stack exchange](http://stackexchange.com/users/18290/atilla-ozgur?tab=reputation)
5. [linkedin](http://www.linkedin.com/in/atiozgur)

## References
Available upon request.

## Languages

- Turkish (Native)
- English (C2)
- German (B1, Telc certification)
- Bulgarian (A1)

[Long Version of My Resume](https://docs.google.com/document/d/1sJCHMVFrh0yWYBo6lHNOUm1UgHN2dsGzuYlK8a2rhK8/edit?usp=drive_link)

