# Lebenslauf von Atilla Özgür (Phd)


{{< include resume/email-phone.md >}}


- (Letzte Aktualisierung 2025-03-08)


{{< include resume/short-summary-de.md >}}


# Ausbildung


| Universität                       | Departement             | Abschluss    | Start | Ende  |
|----------------------------------|------------------------|----------|-------|------|
| Middle East Technical University | Elektrotechnik  | Bachelor | 1995  | 2003 |
| Atılım University                | Computertechnik  | Master   | 2004  | 2007 |
| Middle East Technical University |Medizinische Informatik (unvollständig)  | Master   | 2005  | 2008 |
| Başkent University               | Elektrotechnik | PHD      | 2007  | 2017 |


# Berufliche Laufbahn

| Titel             | Firma     | Start   | Ende |
|-------------------|-------------|---------|-----|
| Postdoktorand  | Constructor Universität Bremen - Mathematics and Logistics| 04/2024 | 03-2026 |
| Adjunct Professor (Part time)   | Ankara Science Universität | 09-2024 | 02-2025 |
| Senior Developer  | SMS Digital | 02-2022 | 03-2024 |
| Lehrbeauftragter (Teilzeit)   | Constructor Universität | 09-2022 | 02-2024 |
| Postdoktorand  | Jacobs Universität Bremen - Mathematics and Logistics| 01/2018 | 01/2022 |
| Datenbankadministrator  | Türkische Arbeitsagentur | 07/2011 | 12/2017 |
| Softwareentwickler und Build-/DevOps-Ingenieur  | Milsoft | 05/2010 | 07/2011 |
| Senior Softwareentwickler  | Tilda Telekom | 10/2009 | 05/2010 |
| Software Trainer  | Freiberuflich | 06/2009 | 10/2009 |
| Software-Projektmanager  | Turksat | 07/2008 | 06/2009 |
| Software-Projektmanager  | Simetri | 09/2006 | 04/2008 |
| Software Trainer  | Netsoft | 10/2005 | 12/2006 |
| Softwareentwickler  | Kale Software | 10/2004 | 10/2005 |
| Softwareentwickler  | Veripark | 06/2003 | 10/2004 |



# Peer-Review-Artikel (SCI-E)

{{< include resume/article-list.md >}}

## Weitere von Fachkollegen begutachtete Artikel


{{< include resume/article-list-other.md >}}


- Siehe andere in meinem [google scholar](https://scholar.google.com.tr/citations?user=Q9ll-kcAAAAJ&hl=en) und [Research Gate](https://www.researchgate.net/profile/Atilla_Oezguer) profile.

# Zertifizierungen - Prüfungen (Die vollständige Historie finden Sie in der Langfassung)

{{< include resume/certificates.md >}}

## Sprachen

{{< include resume/languages-de.md >}}



# Kurse, die ich an Universitäten unterrichtet habe:

{{< include resume/courses-taught-de.md >}}



# Online-Präsenz

{{< include resume/online-presence.md >}}



# Referenzen
Auf Anfrage erhältlich.



[Langfassung meines Lebenslaufs English](https://docs.google.com/document/d/1sJCHMVFrh0yWYBo6lHNOUm1UgHN2dsGzuYlK8a2rhK8/edit?usp=drive_link)

