# Özgeçmiş Atilla Özgür (Phd)

- Mönchengladbach Germany/Ankara Türkiye
- +49 0162 5638824 / +90 0533 2515557
- ati.ozgur@gmail.com / aoezguer@constructor.university


{{< include resume/short-summary-tr.md >}}


## Resmi Eğitim


| Eğitim                       | Bölüm             | Derece   | Başlangıç | Bitiş  |
|----------------------------------|------------------------|----------|-------|------|
| Orta Doğu Teknik Üniversitesi | Elektrik Mühendisliği | Lisans | 1995  | 2003 |
| Atılım Üniversitesi                | Computer Engineering   | Yüksek Lisans   | 2004  | 2007 |
| Orta Doğu Teknik Üniversitesi | Medical Informatics    | Yüksek Lisans   | 2005  | 2008, Incomplete |
| Başkent Üniversitesi               | Elektrik Mühendisliği | PHD      | 2007  | 2017 |


## Çalışma Geçmişi

| Ünvan             | Kurum     | Başlangıç   | Bitiş |
|-------------------|-------------|---------|-----|
| Doktora Sonrası Araştırmacı  | Constructor Üniversitesi Bremen - Mathematics and Logistics| 04/2024 | - |
| Kidemli Yazılım Geliştirici  | SMS Digital | 02-2022 | 03-2024 |
| Doktor Öğretim Üyesi | Ankara Yıldırım Beyazıd Üniversitesi - Bilgisayar Mühendisliği | 06/2021| 02/2022 |
| Doktora Sonrası Araştırmacı  | Jacobs Üniversitesi Bremen - Mathematics and Logistics| 01/2018 | 01/2022 |
| Veritabanı Yöneticisi  | Turkish Labor Agency | 07/2011 | 12/2017 |
|  Yazılım Geliştirici and Build/DevOps Engineer  | Milsoft | 05/2010 | 07/2011 |
| Senior  Yazılım Geliştirici  | Tilda Telekom | 10/2009 | 05/2010 |
| Yazılım Eğitmeni | Freelance | 06/2009 | 10/2009 |
| Yazılım Proje Yöneticisi  | Turksat | 07/2008 | 06/2009 |
| Yazılım Proje Yöneticisi  | Simetri | 09/2006 | 04/2008 |
| Yazılım Eğitmeni  | Netsoft | 10/2005 | 12/2006 |
|  Yazılım Geliştirici  | Kale Yazılım | 10/2004 | 10/2005 |
|  Yazılım Geliştirici  | Veripark | 06/2003 | 10/2004 |



## Hakemli Bilimsel Makaleler (SCI-E)

{{< include resume/article-list.md >}}

## Diğer Hakemli Bilimsel Makaleler

1. Atilla Özgür, Hamit Erdem  Saldırı Tespit Sistemlerinde Kullanılan Kolay Erişilen Makine Öğrenme Algoritmalarının Karşılaştırılması Bilişim Teknolojileri Dergisi, 41-48, 2012
2. Fatih Nar, Osman Erman Okman, Atilla Özgür, M Çetin, “RmSAT-CFAR: Fast and accurate target detection in radar images” in SoftwareX, 2017

- Diğerleri için [google scholar](https://scholar.google.com.tr/citations?user=Q9ll-kcAAAAJ&hl=en) ve [Research Gate](https://www.researchgate.net/profile/Atilla_Oezguer) profiles.

## Sertifikalar- Sınavlar (Tümü için uzun versiyona bakın)


{{< include resume/certificates.md >}}


## Üniversitelerde verdiğim dersler:

{{< include resume/courses-taught-tr.md >}}

## Çevrim içi 

{{< include resume/online-presence.md >}}


## Referanslar

İstek üzerine verilebilir.


## Yabancı diller

- Türkçe (Anadil)
- İngilizce (C2)
- Almanca (B1, Telc certification)
- Bulgarca (A1)

[Özgeçmişin uzun versiyonu](https://docs.google.com/document/d/1sJCHMVFrh0yWYBo6lHNOUm1UgHN2dsGzuYlK8a2rhK8/edit?usp=drive_link)